### PR TITLE
Venn

### PR DESCRIPTION
**Pull request by josephignace**
Venn script added.
Venn and Venn_midpoint outputs (per cohort) show similar counts (±1-3 points difference due to round method).
Total_snomed, Total_hes,Total_death, and total columns are retained for comparison purposes.

### CODE REVIEW

**Comment by venexia** [comment]
Hi @josephignace. I am still getting a discrepancy for the overall total - e.g., for Alzheimer's disease, total_midpoint6=1329 but total_midpoint6_derived=363. I have attached the file [venn_prevax_midpoint6.csv](https://github.com/user-attachments/files/15816659/venn_prevax_midpoint6.csv) that the code returns for your reference. 

What is the difference between the totals with the suffix midpoint6 and midpoint6_derived in this file? If the suffix midpoint6 is actually the original values (i.e., values that are not derived and have no rounding) then they cannot be in the file as we cannot output it. To compare the results before and after disclosure control, you need to compare the two files (`output/venn_[cohort]_midpoint6.csv` and `output/venn_[cohort].csv`). If you want to compare within R then you can make a copy of the dataframe before you start applying disclosure control OR keep everything in one dataframe but select the columns to save to the output.

**Review by venexia — CHANGES_REQUESTED** [review]
Hi @josephignace. I am still getting a discrepancy for the overall total - e.g., for Alzheimer's disease, total_midpoint6=1329 but total_midpoint6_derived=363. I have attached the file [venn_prevax_midpoint6.csv](https://github.com/user-attachments/files/15816659/venn_prevax_midpoint6.csv) that the code returns for your reference.

What is the difference between the totals with the suffix midpoint6 and midpoint6_derived in this file? If the suffix midpoint6 is actually the original values (i.e., values that are not derived and have no rounding) then they cannot be in the file as we cannot output it. To compare the results before and after disclosure control, you need to compare the two files (output/venn_[cohort]_midpoint6.csv and output/venn_[cohort].csv). If you want to compare within R then you can make a copy of the dataframe before you start applying disclosure control OR keep everything in one dataframe but select the columns to save to the output.

**Comment by josephignace** [comment]
Hi @venexia. Are you running the script with the old files? If so, you will have to delete all the files and run everything to get the new numbers (I tested the code 3-4 times before opening the PR). I attached the new file
[venn_prevax_midpoint6.csv](https://github.com/user-attachments/files/15816944/venn_prevax_midpoint6.csv) with the code I tested (again).
I never mentioned that I will leave the not-rounded columns in the files used for output release. When I opened the PR I mentioned that I left the columns for comparison purposes. And just to clarify, each time I tested the code, I compared files within R and after running the pipeline with the dummy data.

**Review by venexia — CHANGES_REQUESTED** [review]
Hi @josephignace. I reran the entire pipeline on the command line using -f and was able to reproduce the csv you sent so I am satisfied that the numbers match before and after rounding. Please remove the the non-rounded variables from the output and then I can approve the request. Many thanks.

**Review by venexia — APPROVED** [review]

**Pull request merged**
